MIMP-12 rio upload
CRSU-Apps/MetaImpact pull request #11
Opened 2024-03-08 11:52 UTC by JanionNevill

Injected data page from MetaPairwise. Some further tidying-up to fix an error when running the frequentist analysis.

2024-03-08 14:45 UTC, tommorris168 commented
Am I supposed to be reviewing only the last three commits? Those are the only ones that seem relevant to this task.
Also there is no dev branch.

2024-03-11 09:01 UTC, JanionNevill commented
> Am I supposed to be reviewing only the last three commits? Those are the only ones that seem relevant to this task. Also there is no dev branch.

Yes, last 3 commits only. Thanks Tom :)

2024-03-11 13:23 UTC, tommorris168 requested changes
General comment: on the Data tab, the example datasets on the bottom left are ordered as continuous then binary, whereas in the format requirements on the right they are ordered as binary then continuous. One could be changed for consistency.

2024-03-11 13:23 UTC, tommorris168 commented on tests/testthat/helper-formatting.R
> +  is_char = is.character(vector)
These = should all be <-

2024-03-11 16:17 UTC, tommorris168 commented
One more thing: you should add yourself as an author.

2024-03-12 13:08 UTC, tommorris168 approved these changes
Yes

2024-03-12 13:08 UTC, tommorris168 approved these changes
Yes?

2024-03-12 13:09 UTC, tommorris168 commented
For some reason when I try to accept the changes it is just adding a comment.

2024-03-12 13:17 UTC, tommorris168 commented
Also, there isn't a "resolve conversation" option for my comments. I don't know what I should be doing for that to appear.

2024-03-12 13:44 UTC, merged