MIMP-17 Fix funnel plot bug
CRSU-Apps/MetaImpact pull request #22
Opened 2024-12-10 15:36 UTC by BalancedmonkeY

Fixed a bug in plotting the simulated trials on the extended funnel plot (details in Jira MIMP-17).
Whilst working in file `SampleSizeFunctions.R`, improved function documentation.

Further improvements that were linked to the fix (saving the simulation data to text files) has been documented as a task Jira MIMP-20.

2024-12-16 08:55 UTC, JanionNevill requested changes
Minor changes to the Roxygen comments.

I tried following the reproduction steps in the Jira issue, but I'm getting a different error before even hitting the end of the steps:
```
Error in metapow: unused arguments (chains = chains(), iter = iter(), warmup = burn(), prior = prior())
```

2024-12-16 16:21 UTC, BalancedmonkeY commented on R/SampleSizeFunctions.R
> +metasim <- function(es, tausq, var, model, n, data, measure) {
It should do? I've clarified that the contents are different depending on `measure`.

But it should be returned by 
`new <- list(new.events.t = new.events.t, new.events.c = new.events.c, new.effect = new.effect)` or `new <- list(new.mean.t = new.mean.t, new.stdev.t = new.stdev.t, new.mean.c = new.mean.c, new.stdev.c = new.stdev.c)`, then `return(new)`

2024-12-18 09:42 UTC, JanionNevill commented on R/SampleSizeFunctions.R
> +metasim <- function(es, tausq, var, model, n, data, measure) {
`CutOffSettings()` at the bottom still needs Roxygen comments fixing. Sorrythaaaanks

2024-12-18 09:58 UTC, JanionNevill approved these changes
Just one other Roxygen fix

2024-12-20 15:21 UTC, merged